//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EKZAMENADONET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Good
    {
        public int goodId { get; set; }
        public string goodTitle { get; set; }
        public string producer { get; set; }
        public string description { get; set; }
        public byte[] photo { get; set; }
        public int characteristicId { get; set; }
        public int categoryId { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Characteristic Characteristic { get; set; }
    }
}
